OSASINFRA-3499: prevents HA deployments for now
shiftstack/hypershift pull request #3
Opened 2024-06-17 19:20 UTC by EmilienM

**What this PR does / why we need it**:

HA can't work right now because OSP clouds don't always have multiple AZ and HCP sets the topology zone label for pods in restrictive mode.

So for the dev preview we will restrict the install to SingleReplica.

2024-06-17 19:22 UTC, EmilienM commented
/cc MaysaMacedo mdbooth 
This isn't really fixing the issue but I think it's an acceptable workaround for now which removes an hack that would never merge in master anyway.

2024-06-18 12:54 UTC, mdbooth requested changes
This isn't correct. It's the *management* cluster that doesn't support HA, not the workload cluster.

2024-06-18 13:37 UTC, EmilienM commented
@mdbooth please review again

2024-06-18 13:42 UTC, mdbooth approved these changes
/lgtm

2024-06-18 13:44 UTC, merged